services:
  app:
    build: .
    container_name: arranchamento_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - NR_DIAS=${NR_DIAS}
      - LOCK=${LOCK}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: arranchamento_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./arranchamento.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

  phpmyadmin:
    image: phpmyadmin:5
    container_name: arranchamento_pma
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:

